### ISSUE TITLE
Property rdf:rest not found while printing Ask

### ISSUE THREAD

**Issue by jirihelmich** [spinrdf/spinrdf#11]
I have the following sample scala code:

```
val constructModel = ModelFactory.createDefaultModel()
val arqQuery = ARQFactory.get().createQuery(constructModel, "CONSTRUCT { ?s ?p ?o } WHERE { ?s ?p ?o. }")
val construct = new ARQ2SPIN(constructModel).createQuery(arqQuery, null).asInstanceOf[Construct]
val ask = SPINFactory.createAsk(ModelFactory.createDefaultModel(), construct.getWhere)
val askString = ARQFactory.get().createCommandString(ask)
```

Assuming it is a correct usage of the API (I found it hard to find any docs other than autogenerated), then I always end up by the last line triggering the following exception:

```
Caused by: org.apache.jena.shared.PropertyNotFoundException: http://www.w3.org/1999/02/22-rdf-syntax-ns#rest
	at org.apache.jena.rdf.model.impl.ModelCom.getRequiredProperty(ModelCom.java:1231)
	at org.apache.jena.rdf.model.impl.ResourceImpl.getRequiredProperty(ResourceImpl.java:172)
	at org.apache.jena.rdf.model.impl.RDFListImpl.getTail(RDFListImpl.java:249)
	at org.apache.jena.rdf.model.impl.RDFListImpl$RDFListIterator.next(RDFListImpl.java:1220)
	at org.apache.jena.rdf.model.impl.RDFListImpl$RDFListIterator.next(RDFListImpl.java:1183)
	at org.topbraid.spin.model.impl.ElementListImpl.getElements(ElementListImpl.java:75)
	at org.topbraid.spin.model.impl.ElementListImpl.print(ElementListImpl.java:115)
	at org.topbraid.spin.model.impl.AbstractSPINResourceImpl.printNestedElementList(AbstractSPINResourceImpl.java:132)
	at org.topbraid.spin.model.impl.QueryImpl.printWhere(QueryImpl.java:224)
	at org.topbraid.spin.model.impl.AskImpl.printSPINRDF(AskImpl.java:32)
```

Therefore, I assume that the getWhere method somehow produces an `ElementList` that is not valid for Jena.

Am I doing something wrong or is this really a bug? Is there any workaround? Using spin-rdf-2.0.0.

**Comment by jirihelmich** [comment]
I assume the bug would come from `QueryImpl.getWhere`

```
Element element = SPINFactory.asElement(whereS.getResource());
return (ElementList)element;
```

**Comment by keski** [comment]
I believe this is related to how the `WHERE` clause is being serialized. You are creating the `ASK` query in a different model and when the `ARQFactory` attempts to iterate the `ElementList` it does not attempt to resolve the nodes in the old model. So, with the current SPIN implementation I think you need to stick with a single model or "copy" the relevant `WHERE` parts of the model (not sure how that will work with respect to the blank nodes in the list though).
